package main

import (
	"bufio"
	"fmt"
	"os"
)

// ProgramListing is the list of the lines of the program.
type ProgramListing [65536]string

// These are the opcodes of the bytecode generated by the assembler.
const (
	opPush  = 0x01
	opPop   = 0x02
	opJump  = 0x03
	opAdd   = 0x04
	opSub   = 0x05
	opMul   = 0x06
	opDiv   = 0x07
	opLoad  = 0x08
	opStore = 0x09
	opPeek  = 0x0a
	opDup   = 0x0b
	opPrint = 0x0c
)

var vm VirtualMachine
var pl ProgramListing
var plInstrCount int

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: gotinyvm progname.bc")
		os.Exit(1)
	}
	start()
	fmt.Println("\nOK.")
}

func start() {
	vm = *NewVirtualMachine()
	loadProgram(os.Args[1])
	asm := NewAssembler()
	vm.Instructions = asm.Assemble(pl, plInstrCount)
	err := vm.runProgram()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

// loadProgram reads the program file and stores it as the ProgramListing.
// This function also sets the vm instruction count and ProgramListing instruction count.
func loadProgram(path string) {
	f, err := os.Open(path)
	if err != nil {
		fmt.Println("Unable to read program file,", path)
		os.Exit(1)
	}
	scanner := bufio.NewScanner(f)
	i := 0
	for scanner.Scan() {
		//vm.Instructions[i] = scanner.Text()
		pl[i] = scanner.Text()
		i++
	}
	vm.InstructionCount = i
	plInstrCount = i
}
